version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - python -m pip install --upgrade pip
      - pip install flake8 pytest
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  pre_build:
    commands:
      - echo "Testing for syntax errors"
      - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  build:
    commands:
      - echo "Running unittests"
      - pytest -v --cov
  post_build:
    commands:
      - echo "Tests run succesfully"
